#!/usr/bin/python

import sys
from datetime import datetime, time, date
from datetime import timedelta
date_today = datetime.today()

first_day = date_today.replace (day=1)
first_day1 = first_day.strftime('%d')

current_month = date_today.month

if current_month == 12:
	next_year = date_today.year + 1
	next_date = date_today.replace(year=next_year,month=1,day=1)
else:
	next_month = current_month + 1
	next_date = date_today.replace(month=next_month,day=1)

last_day = next_date+timedelta(days = -1)
last_day1 = last_day.strftime('%d')

month = last_day.strftime('%B')

print "%s's first day %s" %(month,first_day1)
print "%s's last day %s" %(month,last_day1)