#!/usr/bin/python
import sys, gzip, argparse
parser = argparse.ArgumentParser(description="Displays the contents of a file or gzip file")
group = parser.add_mutually_exclusive_group()
group.add_argument("-v", "--verbose", action="store_true")
parser.add_argument("filename", help="The filename whose content is to be shown")
args = parser.parse_args()
#arg1 = str(sys.argv)
#print arg1
#filename = str(sys.argv[1])
if args.verbose:
	if args.filename.endswith('gz'):
		f = gzip.open(args.filename,'r')
		content = f.read()
		print "The content of the gz files is : \n%s" %content
		f.close()
	else:	
		f = open(args.filename,'r')
		content = f.read()
		print "The content of the file is : \n%s" %content
		f.close()
else:
	if args.filename.endswith('gz'):
		f = gzip.open(args.filename,'r')
		content = f.read()
		print content
		f.close()
	else:	
		f = open(args.filename,'r')
		content = f.read()
		print content
		f.close()
