#!/usr/bin/python
import sys, gzip
#arg1 = str(sys.argv)
#print arg1
filename = str(sys.argv[1])
if filename.endswith('gz'):
	f = gzip.open(filename,'r')
else:	
	f = open(filename,'r')
content = f.read()
print content
f.close()
