#!/usr/bin/python
import sys, gzip
string = str(sys.argv[1])
filename = sys.argv[2]
if filename.endswith('gz'):
	f = gzip.open(filename, 'r')
else:	
	f = open (filename, 'r')
for line in f:
	if string in line:
		print line
f.close	