#!/usr/bin/python
import sys, gzip
filename = str(sys.argv[1])
if filename.endswith('gz'):
	f = gzip.open(filename,'r')
else:
	f = open (filename,'r')
counter = 0
for line in f:
	counter += 1
print counter
f.close()
