#!/usr/bin/python
import sys, zipfile
filename = str(sys.argv[1])
#if filename ends
#f = zipfile.ZipFile(filename,'r')
f = open (filename,'r')
for line in f:
	line = line[0:-1]
#	total = line + 1
	print line
f.close()
