#!/usr/bin/python

import sys, os, subprocess
git_backup = sys.argv[1]
git_url = sys.argv[2]
cmd1 = "tar -xf %s " %(git_backup)
p = subprocess.call(cmd1,shell=True)
directory = git_backup[:-22]
print directory
directory = "%s/%s" %(os.getcwd(),directory)
print directory
os.chdir(directory) 
cmd2 = "git push --mirror %s" %(git_url)
p = subprocess.call(cmd2,shell=True)


