#!/usr/bin/python

import sys, os, subprocess, datetime,time
date = time.time()
date = datetime.datetime.fromtimestamp(date).strftime('%Y%m%d%H%M%S')
username = sys.argv[1]
username = '-u%s' %username
passw = sys.argv[2]
passw = '-p%s' %passw
db = sys.argv[3]
filename = '%s.sql' %date
port = sys.argv[4]
port = '--port=%s' %port
list1 = ['mysqldump', '-v', username , passw , db, port]
p1 = subprocess.Popen( list1 , stdout=subprocess.PIPE).communicate()[0]
f = open (filename,'w')
g = f.write(p1)
f.close