#!/usr/bin/python
import subprocess, pprint
subprocess.call('exit 1', shell=True)
ps = subprocess.Popen(['cat','/etc/passwd'] , stdout=subprocess.PIPE)
ps1 = ps.communicate()[0]
ps1 = ps1.split('\n')
for x in ps1:  
	if x.endswith('false'): 
		pass
	else:
		x = x.split(':')[0]
		print x